// This is an autogenerated file from Firebase Studio.

import { initializeApp, getApps, getApp } from "firebase/app";
import { getAuth } from "firebase/auth";

const firebaseConfig = {
  projectId: "studio-3657521221-d612e",
  appId: "1:178968479488:web:9ccedca68620490e79d5e5",
  storageBucket: "studio-3657521221-d612e.firebasestorage.app",
  apiKey: "AIzaSyBTZaJyyb29f0ZBElswfl0y3k1AN0FEDso",
  authDomain: "studio-3657521221-d612e.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "178968479488",
};

// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const auth = getAuth(app);

export { app, auth };
